# Site settings
title: GOTDict
description: "Kindle dictionary for A Song of Ice and Fire."
lang: "en"
author: "Various"
baseurl: "/gotdict/" # the subpath of your site, e.g. /blog/
url: "http://wjdp.github.io" # the base hostname & protocol for your site
website: "https://wjdp.github.io/gotdict" # For issue posting

# Build settings
# skip_autolinker: true

# Prevents excerpts from being generated (wasted 50s+ on build)
# See https://github.com/jekyll/jekyll/pull/1386
markdown: kramdown
excerpt_separator: ""

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - tmp

destination: _output

collections:
  definitions:
    output: true
    permalink: site/defs/:path.html

defaults:
  # Shows
  - scope:
      path: "dict"
    values:
      layout: ebook
  - scope:
      path: ""
      type: definitions
    values:
      layout: definition

image:
  source: images
  presets:
    sigil:
      attr:
        class: sigil
        width: 51
        height: 56
        align: middle
    sigil_inline:
      attr:
        class: sigil-inline
        width: 30
        height: 33
        align: middle
